import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [isMenuOpened, setIsMenuOpened] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Menta</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mb-128 py-16">
        <div className="container-fluid">
          <div className="row justify-content-between align-items-center">
            <div className="col-auto display-less-lg-none">
              <Image
                src="/Menta_logo_RGB_Lilla.svg"
                alt="Menta"
                width="196px"
                height="77px"
              />
            </div>
            <div className="col-auto display-lg-none">
              <Image
                src="/Menta_logo_RGB_Lilla.svg"
                alt="Menta"
                width="140px"
                height="55px"
              />
            </div>
            <div className="col-auto display-less-lg-none">
              <div className="row align-items-center">
                <div className="col-auto">
                  <a href="#" className="link c-primary-5 px-16">
                    Behandling
                  </a>
                </div>
                <div className="col-auto">
                  <a href="#" className="link c-primary-5 px-16">
                    Om Menta
                  </a>
                </div>
                <div className="col-auto">
                  <a href="#" className="link c-primary-5 px-16">
                    Behandlingssteder
                  </a>
                </div>
                <div className="col-auto">
                  <a
                    href="#"
                    className="btn btn-outlined btn-rounded btn-white ml-16"
                  >
                    Bestill time
                  </a>
                </div>
              </div>
            </div>
            <div className="col-auto display-lg-none">
              <Image
                onClick={() => setIsMenuOpened(true)}
                src="/menu.svg"
                alt="Menta menu"
                width="32px"
                height="32px"
              />
            </div>
            {isMenuOpened ? (
              <div className="menu-wrapper py-16">
                <div className="container-fluid">
                  <div className="row no-gutters justify-content-between align-items-center">
                    <div className="col-auto">
                      <Image
                        src="/Menta_logo_RGB_Lilla.svg"
                        alt="Menta"
                        width="140px"
                        height="55px"
                      />
                    </div>
                    <div className="col-auto">
                      <Image
                        onClick={() => setIsMenuOpened(false)}
                        src="/close.svg"
                        alt="Close Menta menu"
                        width="32px"
                        height="32px"
                      />
                    </div>
                  </div>
                  <div className="row justify-content-between align-items-center">
                    <div className="col-12 text-center mb-48 mt-48">
                      <a href="#" className="link c-primary-5 px-16">
                        Behandling
                      </a>
                    </div>
                    <div className="col-12 text-center mb-48">
                      <a href="#" className="link c-primary-5 px-16">
                        Om Menta
                      </a>
                    </div>
                    <div className="col-12 text-center mb-48">
                      <a href="#" className="link c-primary-5 px-16">
                        Behandlingssteder
                      </a>
                    </div>
                    <div className="col-12 text-center">
                      <a
                        href="#"
                        className="btn btn-outlined btn-rounded btn-white btn-block"
                      >
                        Bestill time
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </header>
      <section className="container mb-128">
        <div className="row">
          <div className="col-12">
            <h1 className="h1 c-white text-center">
              Unikt tilpasset behandling for deg som møter en hverdag med angst
              eller relaterte utfordringer
            </h1>
          </div>
        </div>
      </section>

      <div className="cover cover-image-primary">
        <a href="#" className="btn btn-white btn-rounded cover-btn-top-center">
          Bestill time
        </a>
      </div>

      {/* <section className="section bg-primary-3"></section> */}
      <section className="section rounded-bottom-left bg-primary-3 pt-0">
        <section className="section rounded-bottom-right bg-primary-2 mb-96">
          <div className="container">
            <div className="row justify-content-between">
              <div className="col-12 col-lg-5 mb-48">
                <h2 className="c-primary-1">
                  Ikke la angsten dempe deg lenger enn nødvendig
                </h2>
              </div>
              <div className="col-12 col-lg-6">
                <p className="c-primary-1">
                  Behandlingen vi benytter har vist seg å gi svært gode
                  resultater. Vi er klar over at alle som er rammet av angst,
                  depresjon eller relaterte utfordringer har forsøkt å løse
                  problemene på egen hånd, men uten å lykkes. Mange har mottatt
                  hjelp som ikke har gitt de resultatet en har håpet på. Til
                  tross for dette, ser vi at mulighetene for bedring er svært
                  gode, når en tar i bruk kunnskapsbasert behandling og det gis
                  med nødvendig spisskompetanse (Les mer: våre beste råd til deg
                  som er rammet av psykisk lidelse)
                </p>
              </div>
            </div>
          </div>
        </section>
        <div className="container">
          <div className="row">
            <div className="col-12 mb-48">
              <h2 className="c-primary-1">We mind the Gap</h2>
            </div>
            <div className="col offset-lg-2">
              <p className="c-primary-1">
                En av de største utfordringene innen psykisk helse er knyttet
                til organisering og kvalitetssikring. Selv når det finnes godt
                dokumenterte og effektive behandlingsmetoder er det ofte slik at
                dette ikke når frem til de som er rammet. Når det tilbys er ofte
                kvaliteten begrenset (ref. Mind the gap artikkel). Menta har som
                mål å lukke dette gapet. Vi tar i bruk de metodene som har vist
                seg å gi best resultater og jobber systematisk for å sikre at
                dette gjøres med spisskompetanse, kvalitet og skreddersøm. Vi
                gjennomfører også et systematisk arbeid for å videreutvikler
                behandlingsmetodene, slik at erfaringene vi gjør oss kommer
                fremtidige pasienter til nytte (Les mer om hvordan vi jobber for
                å sikre kvalitet og skreddersøm).
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="section">
        <div className="container">
          <div className="row mb-96">
            <div className="col-12 mb-48">
              <h2 className="c-primary-2">Start en bedre hverdag</h2>
            </div>
            <div className="col-12 col-lg-6 mb-32">
              <p className="c-primary-2">
                For å tilpasse oss dine behov tilbyr vi behandling ved oppmøte,
                som digitale konsultasjoner eller som behandlingsopphold ved
                vårt senter i Bergen. Sammen finner vi den mest effektive
                løsningen for deg (les mer om våre behandlingstilbud)
              </p>
            </div>
            <div className="col-12 col-lg-auto text-center">
              <a
                href="#"
                className="btn btn-outlined btn-rounded btn-white btn-wide"
              >
                Bestill time
              </a>
            </div>
          </div>
          <div className="row align-items-center gap-32 mb-32">
            <div className="col-12 col-lg-auto text-center order-last order-lg-first">
              <a href="#" className="btn btn-rounded btn-secondary btn-wide">
                BERGEN
              </a>
            </div>
            <div className="col">
              <p className="c-primary-2 fw-bold order-first order-lg-last">
                Les mer om vårt behandlingssenter i Bergen
              </p>
            </div>
          </div>
          <div className="row justify-content-right">
            <div className="col-auto">
              <Image
                src="/by_Menta_lilla_RGB.svg"
                alt="Menta"
                width="140px"
                height="101px"
              />
            </div>
          </div>
        </div>
      </section>
      <footer className="py-32">
        <div className="container">
          <div className="row mb-16">
            <div className="col-12">
              <hr className="divider" />
            </div>
          </div>
          <div className="row justify-content-between">
            <div className="col-12 col-lg-auto mb-32">
              <p className="fw-bold c-primary-5">Menta Bergen</p>
              <p className="c-primary-5">Gate</p>
              <p className="c-primary-5">Adresse</p>
              <p className="c-primary-5 mb-32">5000 Bergen</p>
              <p className="c-primary-5">56 32 00 00</p>
            </div>
            <div className="col-12 col-lg-auto">
              <div className="row">
                <div className="col-12 col-lg-auto">
                  <a href="#" className="link c-primary-5 px-0 px-lg-16">
                    Behandling
                  </a>
                </div>
                <div className="col-12 col-lg-auto">
                  <a href="#" className="link c-primary-5 px-0 px-lg-16">
                    Om Menta
                  </a>
                </div>
                <div className="col-12 col-lg-auto">
                  <a href="#" className="link c-primary-5 px-0 px-lg-16">
                    Behandlingssteder
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
